#!/bin/sh

# parity-v0.1
# parity is a script that converts parities for USD, EUR and GBP using google's finance.

LINK="https://www.google.com/finance/converter?a=2&from=USD&to=EUR&meta=ei"

usage () {
    echo "$0 [-h] [-d2e N] [-d2p N] [-e2d N] [-e2p N] [-p2e N] [-p2d N]"
    echo "-h        Show this message"
    echo "-d2e      Convert USD to EUR"
    echo "-d2p      Convert USD to GBP"
    echo "-e2d      Convert EUR to USD"
    echo "-e2p      Convert EUR to GBP"
    echo "-p2e      Convert GBP to EUR"
    echo "-p2d      Convert GBP to USD"
}

hflag=0
d2eflag=0
d2pflag=0
e2dflag=0
e2pflag=0
p2eflag=0
p2dflag=0

while :
do
    case $1 in
        -h)
	    hflag=1
            break;;
        -d2e)
            d2eflag=1
	    number=$2
	    break;;
	-d2p)
	    d2pflag=1
	    number=$2
	    break;;
	-e2d)
	    e2dflag=1
	    number=$2
	    break;;
	-e2p)
	    e2pflag=1
	    number=$2
	    break;;
	-p2e)
	    p2eflag=1
	    number=$2
	    break;;
	-p2d)
	    p2dflag=1
	    number=$2
	    break;;
        *)
            usage
            exit 1
            ;;
    esac
done

if [ $hflag -eq 1 ]; then
    usage
    exit 1
fi

if [ $# -eq 2 ]; then
    if [ $d2eflag -eq 1 ]; then
	LINK=$(echo "$LINK" | sed s"/[0-9]/$number/g")
	curl -L "$LINK" > result 2>/dev/null
	grep -a "<div id=currency_converter_result>" result | sed 's/<[^>]*>//g'
    fi

    if [ $d2pflag -eq 1 ]; then
	LINK=$(echo "$LINK" | sed s"/EUR/GBP/g" | sed s"/[0-9]/$number/g")
	curl -L "$LINK" > result 2>/dev/null
	grep -a "<div id=currency_converter_result>" result | sed 's/<[^>]*>//g'
    fi

    if [ $e2dflag -eq 1 ]; then
	LINK=$(echo "$LINK" | sed s"/EUR/USD/" | sed 1,/USD/{s/USD/EUR/} | sed s"/[0-9]/$number/g")
	curl -L "$LINK" > result 2>/dev/null
        grep -a "<div id=currency_converter_result>" result | sed 's/<[^>]*>//g'
    fi

    if [ $e2pflag -eq 1 ]; then
	LINK=$(echo "$LINK" | sed s"/EUR/GBP/" | sed "s/USD/EUR/" | sed s"/[0-9]/$number/g")
	curl -L "$LINK" > result 2>/dev/null
	grep -a "<div id=currency_converter_result>" result | sed 's/<[^>]*>//g'
    fi

    if [ $p2eflag -eq 1 ]; then
	LINK=$(echo "$LINK" | sed s"/USD/EUR"/ | sed 1,/EUR/{s/EUR/GBP/} | sed s"/[0-9]/$number/g")
	curl -L "$LINK" > result 2>/dev/null
	grep -a "<div id=currency_converter_result>" result | sed 's/<[^>]*>//g'
    fi

    if [ $p2dflag -eq 1 ]; then
	LINK=$(echo "$LINK" | sed "s/USD/GBP/" | sed "s/EUR/USD/" | sed s"/[0-9]/$number/g")
	curl -L "$LINK" > result 2>/dev/null
	grep -a "<div id=currency_converter_result>" result | sed 's/<[^>]*>//g'
    fi
    rm result
    exit 0
fi

