#!/bin/sh

# parity-v0.1
# parity is a script that converts parities for USD, EUR and GBP using google's finance.

LINK="https://www.google.com/finance/converter?a=2&from=USD&to=EUR&meta=ei"

usage () {
    echo "$0 [-h] [-d2e N] [-d2p N] [-e2d N] [-e2p N] [-p2e N] [-p2d N]"
}

hflag=0
d2uflag=0
d2pflag=0
e2dflag=0
e2pflag=0
p2eflag=0
p2dflag=0

while :
do
    case $1 in
        -h)
	    hflag=1
            break;;
        -d2e)
            d2eflag=1
	    number=$2
	    break;;
	-d2p)
	    d2pflag=1
	    number=$2
	    break;;
	-e2d)
	    e2dflag=1
	    number=$2
	    break;;
	-e2p)
	    e2pflag=1
	    number=$2
	    break;;
	-p2e)
	    p2eflag=1
	    number=$2
	    break;;
	-p2d)
	    p2dflag=1
	    number=$2
	    break;;
        *)
            usage
            exit 1
            ;;
    esac
done

if [[ $hflag -eq 1 ]];
then
    usage
    exit 1
fi

if [[ $# -eq 2 ]]; then
    if [[ $d2eflag -eq 1 ]]; then
	LINK=$(echo "$LINK" | sed s"/[0-9]/$number/g")
	curl -L $LINK > result 2>/dev/null
	grep "\<div id\>" result | sed -e 's/\(<div id=currency_converter_result>\|<span class=bld>\)//g' -e 's/<*.\{5\}>//'
    fi

    if [[ $d2pflag -eq 1 ]]; then
	LINK=$(echo "$LINK" | sed s"/EUR/GBP/g" | sed s"/[0-9]/$number/g")
	curl -L $LINK > result 2>/dev/null
	grep "\<div id\>" result | sed -e 's/\(<div id=currency_converter_result>\|<span class=bld>\)//g' -e 's/<*.\{5\}>//'
    fi

    if [[ $e2dflag -eq 1 ]]; then
	LINK=$(echo "$LINK" | sed s"/EUR/USD/" | sed 1,/USD/{s/USD/EUR/} | sed s"/[0-9]/$number/g")
	curl -L $LINK > result 2>/dev/null
	grep "\<div id\>" result | sed -e 's/\(<div id=currency_converter_result>\|<span class=bld>\)//g' -e 's/<*.\{5\}>//'
    fi

    if [[ $e2pflag -eq 1 ]]; then
	LINK=$(echo "$LINK" | sed s"/EUR/GBP/" | sed "s/USD/EUR/" | sed s"/[0-9]/$number/g")
	curl -L $LINK > result 2>/dev/null
	grep "\<div id\>" result | sed -e 's/\(<div id=currency_converter_result>\|<span class=bld>\)//g' -e 's/<*.\{5\}>//'
    fi

    if [[ $p2eflag -eq 1 ]]; then
	LINK=$(echo "$LINK" | sed s"/USD/EUR"/ | sed 1,/EUR/{s/EUR/GBP/} | sed s"/[0-9]/$number/g")
	curl -L $LINK > result 2>/dev/null
	grep "\<div id\>" result | sed -e 's/\(<div id=currency_converter_result>\|<span class=bld>\)//g' -e 's/<*.\{5\}>//'
    fi

    if [[ $p2dflag -eq 1 ]]; then
	LINK=$(echo "$LINK" | sed "s/USD/GBP/" | sed "s/EUR/USD/" | sed s"/[0-9]/$number/g")
	curl -L $LINK > result 2>/dev/null
	grep "\<div id\>" result | sed -e 's/\(<div id=currency_converter_result>\|<span class=bld>\)//g' -e 's/<*.\{5\}>//'
    fi
    rm result
    exit 0
fi

