#!/bin/sh

# sext (subextract) is a simple script to extract subtitles from mkv files
# This script needs mkvtoolnix-cli to work properly
# See here: https://www.bunkus.org/videotools/mkvtoolnix/index.html

# check if mkvextract and mkvinfo are installed on your system

extract=$(which mkvextract)
info=$(which mkvinfo)

if [ -z "$extract" ];
then
    echo "mkvextract not found on your system, please install mkvtoolnix-cli"
    exit 1
fi

if [ -z "$info" ];
then
    echo "mkvinfo not found on your system, please install mkvtoolnix-cli"
    exit 1
fi

#-------------------------------------------------------------------------------
# functions
#-------------------------------------------------------------------------------

usage () {
    echo "Usage: $0 [-h] [-e file.mkv] [-i file.mkv]"
    echo "-h        show this message"
    echo "-i        retrieve mkv file information"
    echo "-e        extract the #2 .ass subtitles from the mkv file"
}
    
getinfo() {
    mkvinfo $fl
}

xtract_ass() {
    resulting_file=$(basename -s .mkv $fl) #remove file extention
    resulting_file+=".ass" # resulting filename
    track+=":$resulting_file"
    echo "extracting to $resulting_file"
    mkvextract tracks $fl $track
}

#-------------------------------------------------------------------------------
# Argument parsing
#-------------------------------------------------------------------------------

iflag=0
eflag=0

while :
do
    case $1 in
        -h)
            usage
            exit 0
            ;;
        -i)
            iflag=1
	    fl=$2
	    getinfo $fl
            break
            ;;
        -e)
            eflag=1
	    track="2" # default track to extract is 2
	    fl=$2
            break
            ;;

        *)
            usage
            exit 1
            ;;
    esac
done    

if [ $iflag -eq 1 -a $eflag -eq 0 -a $# -eq 2 ];
then
    getinfo
    exit 0
elif [ $eflag -eq 1 -a $iflag -eq 0 -a $# -eq 2 ];
then
    xtract_ass $fl $track
else
    echo "Wrong usage"
    usage
    exit 1
fi
